version: 1
disable_existing_loggers: False

loggers:
  root:
    level: INFO
    handlers: [console_handler, file_handler]
    propagate: no

handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: console_formatter
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: file_formatter
    filename: ./app.log
    mode: a
    encoding: utf8

formatters:
  console_formatter:
    (): colorlog.ColoredFormatter
    datefmt: "%Y-%m-%d %H:%M:%S"
    format: "%(asctime)s - %(name)s - %(log_color)s%(levelname)s - %(module)s:%(lineno)d - %(message)s"
    log_colors:
      DEBUG: green
      INFO: blue
      WARNING: yellow
      ERROR: red
      CRITICAL: bold_red
  file_formatter:
    datefmt: "%Y-%m-%d %H:%M:%S"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s:%(lineno)d - %(message)s"
