
name: Zen Study Lofi Playlist
public: true
collaborative: false
description: このプレイリストでは、作業用や勉強用にLofi-Hiphopを中心にトラックを公開しています。This playlist features tracks primarily in the Lofi-Hiphop genre, ideal for work or study purposes.
cover_image_path: cover_imgs/purple.webp


# for recommendation
seed_artists:
  - "7185Q95lPFld0aoPqO6e0U" # blue_wednesday
seed_tracks:
  # - "7fFwkEjPSEapRqQRSOH8uL"
seed_genres:
  # - "soul"
limit: 50
country:
audio_features: {}
  # min_danceability: 0.6
  # target_danceability: 0.8
  # min_speechiness: 0.8
